rec
xiachufang/pylogrotate pull request #6
Opened 2017-03-27 11:47 UTC by fjkfwz

2017-03-27 12:22 UTC, morefreeze requested changes

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +        raise TypeError("time_begin and time_end must be type of datetime.datetime")
split_datetime

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +    parser.add_argument('-t', '--tags', nargs='+', type=list, help='need to split the files log marked.')
type=str
是list的话，结果会是[['1'], ['2'], ['3], ]这样的

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +            log_matrix.append(log_line)
是不是应该放在L106 整个if的后面，要不第一条大于5分钟的也会被写入

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +                log_matrix = list()
最后for外面应该还有一次写入吧

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +            raise SyntaxError
为什么要raise另一个异常？
这应该忽略异常继续吧

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +                    for _log_line in log_matrix:
f.writelines(log_matrix) ?

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +                        f.writelines(_log_line)
这么写不对吧，是不是字符串每个字符是一行

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +        self.file = gzip.open(file_path, mode='wb')
用'ab'吧 这次的情况是从中间断，原来的文件还有点数据

2017-03-27 12:22 UTC, morefreeze commented on pylogrotate/rec.py
> +        self.file = gzip.open(file_path, mode='wb')
还有个问题，Reader和Writer可能是同一个文件吧，那会不会有问题

2017-05-31 10:06 UTC, ushuz commented
这个干嘛的？

2017-05-31 10:08 UTC, morefreeze commented
@ushuz 日志堆积后重切日志的
@fjkfwz 这两天改下上线吧

2017-06-05 08:25 UTC, gfreezy commented
这个是解析了日志内容吧。
pylogrotate不能日志格式做任何假设，否则就变成只能用在某种日志格式的日志上了。

2017-07-07 06:15 UTC, closed without merging